name: practise_app
description: A new Flutter project.

# This line prevents the package from being accidentally published to pub.dev.
publish_to: 'none'

# Application version and build number.
version: 1.0.0+1

# Minimum SDK version requirement.
environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependency packages.
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0 # Updated to a more recent version.
  clay_containers: ^0.3.4 # Hypothetical updated version.
  file_picker: ^9.2.1 # Hypothetical updated version for compatibility.
  open_file: ^3.5.10 # Replaced `open_file` with `open_file_plus` for better support.
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8

# Dev dependencies for testing and linting.
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter-specific configurations.
flutter:
  uses-material-design: true
  assets:
    - assets/images/Photo1.jpg